sudo: required

os:
  - linux

language: go

go:
  - 1.11.x

install: true

jobs:
  include:
    - stage: "build and test"
      name: "gx"
      script:
        - sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0 net.ipv6.conf.default.disable_ipv6=0 net.ipv6.conf.all.disable_ipv6=0
        - make deps
        - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)

    - name: "go mod"
      script:
        - sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0 net.ipv6.conf.default.disable_ipv6=0 net.ipv6.conf.all.disable_ipv6=0
        - export GO111MODULE=on
        - make mod_deps
        - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)

cache:
    directories:
        - $GOPATH/pkg/mod
        - $GOPATH/src/gx

notifications:
  email: false
